### ISSUE TITLE
gRPC pkg versions: make it easier/more uniform to introduce new gRPC languages

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#498]
**Dart** and **Kotlin** are in need of specifying their own gRPC package versions. Currently, gRPC package versions are declared as site parameters in the config file like this:

```yaml
  grpc_release_tag: v1.33.1
  grpc_java_release_tag: v1.33.1
  grpc_go_release_tag: v1.31.0
```

We can do better than to embed the language inside the id, using a YAML map, for example.
