### ISSUE TITLE
Fix broken links as reported by htmltest@HEAD

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#831]
Using these extra `htmltest` config parameters:

```yaml
CheckDoctype: false # Sadly, this is only because of `google*.html`
IgnoreInternalURLs:
  - api
  - daily-builds
  - /docs/languages/csharp/daily-builds/
  - /docs/languages/php/daily-builds/
  - /docs/languages/python/daily-builds/
  - /docs/languages/ruby/daily-builds/
  - /grpc/python/grpc.html?#grpc.UnaryUnaryMultiCallable
  - /grpc/python/grpc.html?#grpc.UnaryStreamMultiCallable
  - /grpc/python/grpc.html?#grpc.StreamUnaryMultiCallable
  - /grpc/python/grpc.html?#grpc.StreamStreamMultiCallable
  - /grpc/python/_modules/grpc.html#Server
  - /grpc/cpp/classgrpc_1_1_completion_queue.html
 ```

Here is the command output:

```console
$ HTMLTEST=~/git/misc/htmltest/bin/htmltest make check-internal-links
/Users/chalin/git/misc/htmltest/bin/htmltest
htmltest started at 02:45:31 on public
========================================================================
docs/platforms/android/kotlin/quickstart/index.html
  target does not exist --- docs/platforms/android/kotlin/quickstart/index.html --> ../basics/
docs/index.html
  target does not exist --- docs/index.html --> /faq/
docs/what-is-grpc/faq/index.html
  target does not exist --- docs/what-is-grpc/faq/index.html --> /contribute/
docs/languages/java/generated-code/index.html
  target does not exist --- docs/languages/java/generated-code/index.html --> /docs/languages/android/basics/#generating-client-code
showcase/index.html
  hash does not exist --- showcase/index.html --> /docs/languages/cpp/#dev-stories
  hash does not exist --- showcase/index.html --> /docs/languages/python/#dev-stories
  hash does not exist --- showcase/index.html --> /docs/languages/csharp/#dev-stories
========================================================================
✘✘✘ failed in 211.943785ms
7 errors in 134 documents
```
